google/labs-prototypes

- package-lock.json
- seeds/graph-playground/coffee-prompt.txt
- seeds/graph-playground/first-question.txt
- seeds/graph-playground/graphs/coffee-bot.json
- seeds/llm-starter/src/core.ts
- seeds/llm-starter/src/nodes/text-asset.ts
This is helpful when dealing with very large prompts.
> Add a text-asset node for loading text  from a file

- package-lock.json
- seeds/breadboard/docs/tutorial/README.md
- seeds/breadboard/docs/tutorial/news-summarizer.json
- seeds/breadboard/docs/tutorial/tutorial-7b.js
- seeds/graph-playground/docs/graphs/react-with-slot.md
- seeds/graph-playground/graphs/call-react-with-slot.json
- seeds/graph-playground/graphs/react-with-slot.json
- seeds/graph-playground/src/boards/accumulating-context.ts
- seeds/graph-playground/src/boards/call-react-with-slot.ts
- seeds/graph-playground/src/boards/react-with-slot.ts
- seeds/graph-playground/src/index.ts
- seeds/llm-starter/src/nodes/append.ts
- seeds/llm-starter/tests/nodes/append.ts
- seeds/node-nursery/package.json
> [llm-starter] Teach `react-with-slot` to use `append`.

- .github/workflows/labs-prototypes-ci.yml
- docs/contributing.md
- package-lock.json
- package.json
- seeds/breadboard/package.json
- seeds/cloud-function/package.json
- seeds/cloud-function/tests/index.js
- seeds/coffee-bot-board/package.json
- seeds/discovery-types/package.json
- seeds/graph-integrity/package.json
- seeds/graph-playground/package.json
- seeds/graph-playground/wild/syntax/wires-proposal-2.ts
- seeds/graph-runner/package.json
- seeds/llm-starter/package.json
- seeds/node-nursery/package.json
- seeds/palm-lite/package.json
- seeds/web-demo/package.json
- seeds/web-demo/vite.config.ts
- templates/blank/package.json
The CI is configured to run the actions supported by Node JS version 19.x. The steps covered are as follows
- Clean installing the dependencies (I have added the npm package npm ci) for this step
- Generating the build 
- Running the tests
- Checking the code quality using eslint. Command used: `FORCE_COLOR=1 eslint . --ext .ts`
- Checking the code formatting using prettier. Command used : `prettier --check --config .prettierrc seeds/**/*.ts`
- The CI will fail if anyone of the steps fail.
- Added few minor formatting changes and placeholder code on couple of files to pass the CI.
> LP-104: Stand up project infrastructure

- seeds/breadboard/docs/wires.md
Add missing 'not'
Fixes #<issue_number_goes_here>
> Add missing 'not' to wires.md

- seeds/breadboard/docs/nodes.md
Fixes #<issue_number_goes_here>
> Fix code sample in notes.md

- seeds/breadboard/docs/tutorial/README.md
"we've build" -> "we've built"
Fixes #<issue_number_goes_here>
> Update README.md, small typo

- seeds/llm-starter/README.md
> Minor fixes to README.md

- seeds/llm-starter/README.md
> Fixes minor typo in README.md

- seeds/breadboard/docs/tutorial/README.md
> Update README.md to reflect property name used in example.

- seeds/breadboard/README.md
Creates a "Requirements" header to highlight the requirement for node >=19.0
> Update README.md to highlight the requirement for node >=19.0

- seeds/breadboard/.npmrc
- seeds/breadboard/README.md
> Highlight and enforce the requirement for node >=19.0

- seeds/pythonboard/requirements.txt
- seeds/pythonboard/src/breadboard.py
- seeds/pythonboard/src/kit.py
- seeds/pythonboard/src/loader.py
- seeds/pythonboard/src/main.py
Updates the loader in pythonboard to handle graph targets besides file location
> Add kit and loader to pythonboard

- seeds/breadboard/docs/tutorial/README.md
> Update README.md — Adds additional info & instruction on using the `dotenv` package

- seeds/breadboard/docs/tutorial/README.md
> Update README.md to use correct putput/input names for first part of Chapter 5 instructions.

- seeds/chunker-python/pyproject.toml
Added dependencies so they are pulled in during pip install.
> Add dependencies to HtmlChunker distribution configuration.

- seeds/breadboard/.eslintrc
- seeds/breadboard/docs/libraries-as-kits.md
- seeds/breadboard/src/kits/builder.ts
- seeds/breadboard/tests/kits.ts
With this we are able to import any JS lib and
then make nodes out of them.
+ Maps input names to argument positions in the function
+ Maps output to result if Number, String, Array
+ Maps output to Node Output names if an object.
TODO:
> KitBuilder.wrap so that we can call any JS library

- seeds/pythonboard/requirements.txt
- seeds/pythonboard/src/breadboard.py
- seeds/pythonboard/src/kit.py
- seeds/pythonboard/src/loader.py
- seeds/pythonboard/src/main.py
- seeds/pythonboard/src/traversal/iterator.py
Fixes pythonboard not handling node invoke
> Python tweaks

- package-lock.json
- seeds/hello-world/.npmignore
- seeds/hello-world/README.md
- seeds/hello-world/package.json
- seeds/hello-world/src/board.ts
- seeds/hello-world/src/index.ts
- seeds/hello-world/tests/hello-world.ts
- seeds/hello-world/tsconfig.json
- tsconfig.json
I thought it would be handy to have a board checked in that demonstrates the Hello, World case.
> Adds 'Hello, World' board

- seeds/breadboard-web/public/styles/global.css
- seeds/breadboard-web/public/third_party/icons/collapse.svg
- seeds/breadboard-web/public/third_party/icons/expand.svg
- seeds/breadboard-web/src/ui/load.ts
- seeds/breadboard-web/src/ui/start.ts
- seeds/breadboard-web/src/ui/ui-controller.ts
> [breadboard-web] Style board metadata

- seeds/breadboard-web/src/ui/load.ts
Fixes a minor rendering issue in the diagram SVG.
> [breadboard-web] Minor fix for line height in diagram

- .github/workflows/labs-prototypes-ci.yml
- seeds/breadboard-web/src/ui/load.ts
- seeds/breadboard-web/src/ui/toast.ts
- seeds/breadboard-web/src/ui/ui-controller.ts
Makes some minor style tweaks for mobile devices
> [breadboard-web] Mobile style tweaks

- seeds/breadboard-web/public/styles/global.css
- seeds/breadboard-web/src/ui/done.ts
- seeds/breadboard-web/src/ui/index.ts
- seeds/breadboard-web/src/ui/output.ts
- seeds/breadboard-web/src/ui/progress.ts
- seeds/breadboard-web/src/ui/response-container.ts
- seeds/breadboard-web/src/ui/result.ts
- seeds/breadboard-web/src/ui/toast.ts
- seeds/breadboard-web/src/ui/ui-controller.ts
This adds some styles to the each step in the board run. Next step is to style the actual UI elements.
> [breadboard-web] Start styling of steps

- seeds/breadboard-web/index.html
- seeds/breadboard-web/public/styles/global.css
- seeds/breadboard-web/src/index.ts
- seeds/breadboard-web/src/ui/done.ts
- seeds/breadboard-web/src/ui/error.ts
- seeds/breadboard-web/src/ui/input.ts
- seeds/breadboard-web/src/ui/output.ts
- seeds/breadboard-web/src/ui/progress.ts
- seeds/breadboard-web/src/ui/response-container.ts
- seeds/breadboard-web/src/ui/result.ts
> [breadboard-web] Style inputs

- seeds/breadboard-web/public/styles/global.css
- seeds/breadboard-web/src/index.ts
- seeds/breadboard-web/src/ui/response-container.ts
- seeds/breadboard-web/src/ui/result.ts
- seeds/breadboard-web/src/ui/start.ts
- seeds/breadboard-web/src/ui/ui-controller.ts
> [breadboard-web] Style LLM result

- seeds/breadboard-web/public/styles/global.css
- seeds/breadboard-web/src/ui/input.ts
- seeds/breadboard-web/src/ui/output.ts
- seeds/breadboard-web/src/ui/response-container.ts
- seeds/breadboard-web/src/ui/result.ts
> [breadboard-web] Style output nodes

- seeds/breadboard-web/src/index.ts
> [breadboard-web] Ignore stale proxy responses

- seeds/breadboard-web/src/ui/load.ts
> [breadboard-web] Lazy load Mermaid

- seeds/breadboard-web/src/ui/input.ts
- seeds/breadboard-web/src/ui/response-container.ts
Final one for #202 for now. I'll have to have a think about this in context of #239 as there are multiple input types that could be affected.
> [breadboard-web] Tweak-fix the position of input nodes

- seeds/breadboard-ui/CHANGELOG.md
- seeds/breadboard-ui/README.md
Release commit for breadboard-ui
> [breadboard-ui] Publish `0.0.1`

- seeds/breadboard-ui/src/load.ts
Helps with #241 a bit. Not loads, though.
> [breadboard-ui] Make diagrams a bit bigger

- seeds/breadboard-ui/src/load.ts
- seeds/breadboard-ui/src/start.ts
- seeds/breadboard-ui/src/ui-controller.ts
- seeds/breadboard-web/index.html
- seeds/breadboard-web/public/styles/global.css
I've reverted the board selection to a `<select>` so that we have more horizontal space for debugging info.
> [breadboard-ui] Make more vertical space

- seeds/breadboard/docs/tutorial/README.md
First of a few small additions/tweaks to the tutorial as I go through it.
Part of https://github.com/google/labs-prototypes/issues/199
> A few small improvements to the breadboard tutorial

- seeds/breadboard-ui/src/diagram.ts
- seeds/breadboard-ui/src/utils/assertions.ts
> [breadboard-ui] Add mousewheel support

- seeds/breadboard-ui/public/styles/global.css
- seeds/breadboard-ui/src/output.ts
- seeds/breadboard-ui/src/ui-controller.ts
- seeds/breadboard-web/public/styles/global.css
They were taking up a little too much space for my liking!
> [breadboard-ui] Restyle outputs

- seeds/team-experiments/src/types/types.ts
- seeds/team-experiments/src/ui/elements/conversation/conversation.ts
- seeds/team-experiments/src/ui/elements/team-job/team-job.ts
Like so:
```javascript
this.conversation.push({
datetime: new Date(performance.timeOrigin),
who: Participant.USER,
type: ItemType.INPUT,
format: ItemFormat.ENUM,
title: "Which is your favorite fruit?",
options: ["🍓 Strawberry", "🥝 Kiwi", "🍌 Banana", "🍏 Apple"],
});
```
> [team-exp] Add enumerated input support

- seeds/team-experiments/README.md
- seeds/team-experiments/graphs/bgl/insta/chat-with-tools.bgl.json
- seeds/team-experiments/graphs/bgl/insta/get-page.json
- seeds/team-experiments/graphs/bgl/insta/simple-chat.bgl.json
- seeds/team-experiments/src/server/browse.ts
- seeds/team-experiments/src/ui/elements/team-job/team-job.ts
- **Switch to secrets for model.**
- **Introduce `get page` tool.**
- **Add docs.**
> real browse
